project:
  type: website

website:
  title: "LIN517 - Visualization Project"
  navbar:
    left:
      - visualization_final_report.qmd
      - Instructions.qmd

format:
  html:
    theme: dark
    css: styles.css
    toc: true

editor: visual